api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('ws/users/list/', views.user_list, name="ws_users"),
    path('v1/grant_goal/list', views.GrantGoalListAPIView.as_view(), name="grant_goal_list"),
    path('v1/grant_goal/detail/<int:pk>/', views.GrantGoalDetail.as_view(), name="gran_goal_detail"),

    ###v2###
    path('v2/grant_goal/list', views.GrantGoalList2.as_view(), name="grant_goal_list2"),
    path('v2/create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_grantgoal"),
    path('v2/update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grantgoal"),

    #### CLIENTE URLS #####
    path('update/grantgoal/client/<int:pk>/', views.UpdateGrantGoalClient.as_view(), name="gg_update_client"),
    path('detail/grantgoal/client/<int:pk>/', views.DetailGrantGoalClient.as_view(), name="gg_detail_client"),
    path('list/grantgoal/client/', views.ListGrantGoalClient.as_view(), name="gg_list_client"),
    path('create/grantgoal/client/', views.CreateGrantGoalClient.as_view(), name="gg_create_client"),
]

pacs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
]

api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
# Create your models here.



STATE = (
    ('DN', 'Done'),
    ('DG', 'Doing'),
    ('NS', 'NoStared'),
)


class GrantGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal_title = models.CharField(max_length=128)
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=STATE, default="None")
    sprint = models.FloatField(default=0.0)
    slug = models.SlugField(max_length=128)

    def __str__(self):
        return self.goal_title

@receiver(post_save, sender=GrantGoal)
def end_time_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()


GSTATE = (
    ('DNG', 'Done'),
    ('DGG', 'Doing'),
    ('NSG', 'NoStared'),
)

class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gasigned_user')## Pendiente de revisar y modificar
    grant_goal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    goal_name = models.CharField(max_length=128, default="Pretty Cool Goal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=GSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.goal_name
    


SUBSTATE = (
    ('DNS', 'Done'),
    ('DGS', 'Doing'),
    ('NSS', 'NoStared'),
)

class SubGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sasigned_user')## Pendiente de revisar y modificar
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    subgoal_name = models.CharField(max_length=128, default="Pretty Cool SubGoal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=SUBSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.subgoal_name


TSTATE = (
    ('DT', 'Done'),
    ('DGT', 'Doing'),
    ('NST', 'NoStared'),
)

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasigned_user')## Pendiente de revisar y modificar
    subgoal = models.ForeignKey(SubGoal, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=128, default="Pretty Cool SubGoal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=TSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.task_name

api/forms.py
from django import forms

from .models import GrantGoal


class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "goal_title",
            "description",
            "days_duration",
            "status",
            "state",
            "sprint",
            "slug"
        ]


class  UpdateGrantGoalClientForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "goal_title",
            "description",
            "days_duration",
            "status",
            "state",
            "sprint",
            "slug"
        ]
   

api/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core import serializers
from django.views import generic

from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth.models import User

from .serializers import GrantGoalSerializer

from .models import GrantGoal
from .forms import CreateGrantGoalForm, UpdateGrantGoalClientForm

import requests
# Create your views here.

#CREATE
class CreateGrantGoal(generics.CreateAPIView):
    serializer_class = GrantGoalSerializer


#RETRIEVE
class GrantGoalList2(generics.ListAPIView):
    queryset = GrantGoal.objects.all()
    serializer_class = GrantGoalSerializer


class GrantGoalListAPIView(APIView):
    def get(self, request, *args, **kwargs):
        data = GrantGoal.objects.all()
        data = GrantGoalSerializer(data, many=True).data
        return Response(data)
    
class GrantGoalDetail(APIView):
    def get(self, request, pk, *args, **kwargs):
        data = GrantGoal.objects.get(id=pk)
        data = GrantGoalSerializer(data).data
        return Response(data)


#UPDATE
class UpdateGrantGoal(generics.UpdateAPIView):
    serializer_class = GrantGoalSerializer
    queryset = GrantGoal.objects.all()

#DELETE



def user_list(request):
    users = User.objects.all()
    data = serializers.serialize('json', users)
    return HttpResponse(data, content_type='application/json')


##### CLIENTS #####

class CreateGrantGoalClient(generic.View):
    template_name = "api/ggcreatec.html"
    context = {}
    url = "http://localhost:8000/api/v2/create/grantgoal/"
    response = ""
    form = CreateGrantGoalForm()

   
    def get(self, request):
        self.context = {
            'form': self.form
        }
 
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        payload = {
            "goal_title": request.POST["goal_title"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],  
            "status": request.POST["status"],
            "state": request.POST["state"],
            "sprint": request.POST["sprint"],
            "slug": request.POST["slug"],
            "user": request.POST["user"]
        }
        self.response = requests.post(url=self.url, data=payload)
        print(self.response)
        return redirect("/api/list/grantgoal/client")





class UpdateGrantGoalClient(generic.View):
    template_name = "api/ggupdatec.html"
    context = {}
    url_put = "http://localhost:8000/api/v2/update/grantgoal/"
    url_get = "http://localhost:8000/api/v1/grant_goal/detail/"
    response = ""
    form = UpdateGrantGoalClientForm()

    def get(self, request, pk):
        self.url_get = self.url_get + f"{pk}/"
        self.response = requests.get(url=self.url_get)
        self.context = {
            "grantgoal": self.response.json(),
            "form": self.form
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request,pk):
        self.url_put = self.url_put + f"{pk}/"
        payload = {
            "user": request.POST["user"],
            "goal_title": request.POST["goal_title"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],
            "status": request.POST["status"],
            "state": request.POST["status"],
            "slug": request.POST["slug"]
        }
        self.response = requests.put(url=self.url_put, data=payload)
        print(self.response)
        print("-----", self.url_put)
        return render(request, self.template_name, self.context)



class DetailGrantGoalClient(generic.View):
    template_name = "api/ggdetailc.html"
    context = {}
    url = "http://localhost:8000/api/v1/grant_goal/detail/"


    def get(self, request, pk):
        self.url = self.url + f"{pk}/"
        grantgoal = requests.get(url=self.url)
        self.context = {
            "grant_goal": grantgoal.json()
        }
        return render(request, self.template_name, self.context)


class ListGrantGoalClient(generic.View):
    template_name = "api/gglistc.html"
    context = {}
    url = "http://localhost:8000/api/v2/grant_goal/list"


    def get(self, request):
        grantgoal = requests.get(url=self.url)
        self.context = {
            "list_grant_goal": grantgoal.json()
        }
        return render(request, self.template_name, self.context)

templates/api/ggcreatec.html
{% extends 'base/base.html' %}

{% block title %} Create Grant Goal View {% endblock title %}

{% block content %}
  <form action="" class="form-group" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-outline-success">Create</button>
    <a href="{% url 'api:gg_list_client' %}" class="btn btn-outline-warning">Cancel</a>
  </form>
{% endblock content %}

templates/api/ggdetailc.html
{% extends 'base/base.html' %}

{% block title %}DEtail View{% endblock title%}

{% block content %}
    {{ grant_goal }}
    <a href="{% url 'api:gg_list_client' %}" class="btn btn-link">Back To Home</a>
{% endblock content %}

templates/api/gglistc.html
{% extends 'base/base.html' %}

{% block title %}List View{% endblock title%}

{% block newgrantgoal %}
    <a href="{% url 'api:create_grantgoal' %}" class="btn btn-outline-success">Create a GrantGoal</a>
{% endblock newgrantgoal %}

{% block content %}
    <a href="{% url 'api:gg_create_client' %}" class="btn btn-outline-success form-control">Create New GrantGoal</a>
    <br><br>
    <table class="table table-hover">
        <thead>
            <th>Goal Title</th>
            <th>ID</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in list_grant_goal %}
                <tr>
                    <td>{{ gg.goal_title }}</td>
                    <td>{{ gg.id }}</td>
                    <td><a href='{% url "api:gg_detail_client" gg.id %}' class="btn btn-outline-primary">Detail</a></td>
                    <td><a href='{% url "api:gg_update_client" gg.id %}' class="btn btn-outline-warning">Update</a></td>
                    <td><a href='' class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/api/ggupdatec.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE GRANT GOAL CLIENT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="put" class="form">
        {% csrf_token %}
        <label for="user">User</label>
        <input type="text" class="form-control" name="user" id="user" value="{{ grantgoal.user }}">
        <label for="goal_title">GrantGoalTitle</label>
        <input type="text" class="form-control" name="goal_title" id="goal_title" value="{{ grantgoal.goal_title }}">
        <label for="description">GrantGoal Description</label>
        <input type="text" class="form-control" name="description" id="description" value="{{ grantgoal.description }}">
        <label for="days_duration">GrantGoal Days Duration</label>
        <input type="text" class="form-control" name="days_duration" id="days_duration" value="{{ grantgoal.days_duration }}">
        <label for="status">GrantGoal Status</label>
        <input type="text" class="form-control" name="status" id="status" value="{{ grantgoal.status }}">
        <label for="state">GrantGoal State</label>
        <input type="text" class="form-control" name="state" id="state" value="{{ grantgoal.state }}">
        <label for="description">GrantGoal Sprint</label>
        <input type="text" class="form-control" name="sprint" id="sprint" value="{{ grantgoal.sprint }}">
        <label for="description">GrantGoal Slug</label>
        <input type="text" class="form-control" name="slug" id="slug" value="{{ grantgoal.slug }}">
        <br><hr>
        <button type="submit" class="btn btn-outline-primary form-control">Update GrantGoal</button>
        <a href="{% url 'api:gg_list_client' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}